//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCompanyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRESY
    {
        public ADRESY()
        {
            this.PRZESYŁKI = new HashSet<PRZESYŁKI>();
            this.LOKALIZACJE = new HashSet<LOKALIZACJE>();
            this.NADAWCY = new HashSet<NADAWCY>();
            this.ODBIORCY = new HashSet<ODBIORCY>();
            this.PRZESYŁKI1 = new HashSet<PRZESYŁKI>();
            this.PRACOWNICY = new HashSet<PRACOWNICY>();
        }
    
        public decimal ID_ADRESU { get; set; }
        public string ULICA { get; set; }
        public decimal NUMER_DOMU { get; set; }
        public decimal NUMER_MIESZKANIA { get; set; }
        public string KOD_POCZTOWY { get; set; }
        public decimal MIASTO { get; set; }
        public decimal WOJEWÓDZTWO { get; set; }
        public decimal PAŃSTWO { get; set; }
    
        public virtual ICollection<PRZESYŁKI> PRZESYŁKI { get; set; }
        public virtual ICollection<LOKALIZACJE> LOKALIZACJE { get; set; }
        public virtual ICollection<NADAWCY> NADAWCY { get; set; }
        public virtual ICollection<ODBIORCY> ODBIORCY { get; set; }
        public virtual ICollection<PRZESYŁKI> PRZESYŁKI1 { get; set; }
        public virtual ICollection<PRACOWNICY> PRACOWNICY { get; set; }
        public virtual MIASTA MIASTA { get; set; }
        public virtual PAŃSTWA PAŃSTWA { get; set; }
        public virtual WOJEWÓDZTWA WOJEWÓDZTWA { get; set; }

        public static string[] Countries = { "Polska", "Niemcy" };

        public static string[] Regions = { "mazowieckie", "śląskie", "łódzkie", "wielkopolskie", "małopolskie", "pomorskie", "lubelskie", "dolnośląskie", "Bawaria", "Saksonia", "Brandenburgia", "Turyngia" };

        public static string[] Cities = { "Warszawa", "Ostrołęka", "Radom", "Katowice", "Łódź", "Poznań", "Kraków", "Gdańsk", "Gdynia", "Sopot", "Lublin", "Zamość", "Wrocław", "Monachium", "Drezno", "Poczdam", "Erfurt" }; 
    }
}
