//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCompanyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class KONTA
    {
        public KONTA()
        {
            this.NADAWCY = new HashSet<NADAWCY>();
            this.PRACOWNICY = new HashSet<PRACOWNICY>();
        }
    
        public decimal ID_KONTA { get; set; }
        public string NICK { get; set; }
        public decimal TYP_KONTA { get; set; }
        public string HASŁO { get; set; }
        public string MAIL { get; set; }
    
        public virtual ICollection<NADAWCY> NADAWCY { get; set; }
        public virtual ICollection<PRACOWNICY> PRACOWNICY { get; set; }
        public virtual TYPY_KONT TYPY_KONT { get; set; }
    }
}
