//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCompanyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOKALIZACJE
    {
        public LOKALIZACJE()
        {
            this.PACZKI = new HashSet<PACZKI>();
            this.POJAZDY_KURIERSKIE = new HashSet<POJAZDY_KURIERSKIE>();
            this.PRACOWNICY = new HashSet<PRACOWNICY>();
        }
    
        public decimal ID_LOKALIZACJI { get; set; }
        public decimal TYP_LOKALIZACJI { get; set; }
        public decimal ADRES_LOKALIZACJI { get; set; }
    
        public virtual ADRESY ADRESY { get; set; }
        public virtual ICollection<PACZKI> PACZKI { get; set; }
        public virtual ICollection<POJAZDY_KURIERSKIE> POJAZDY_KURIERSKIE { get; set; }
        public virtual ICollection<PRACOWNICY> PRACOWNICY { get; set; }
        public virtual TYPY_LOKALIZACJI TYPY_LOKALIZACJI { get; set; }
    }
}
