//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCompanyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIASTA
    {
        public MIASTA()
        {
            this.ADRESY = new HashSet<ADRESY>();
        }
    
        public decimal ID_MIASTA { get; set; }
        public decimal WOJEWÓDZTWO { get; set; }
        public string MIASTO { get; set; }
    
        public virtual ICollection<ADRESY> ADRESY { get; set; }
        public virtual WOJEWÓDZTWA WOJEWÓDZTWA { get; set; }
    }
}
