//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCompanyApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADRESY> ADRESY { get; set; }
        public DbSet<KONTA> KONTA { get; set; }
        public DbSet<KURIERZY_POJAZDY> KURIERZY_POJAZDY { get; set; }
        public DbSet<LOKALIZACJE> LOKALIZACJE { get; set; }
        public DbSet<MIASTA> MIASTA { get; set; }
        public DbSet<NADAWCY> NADAWCY { get; set; }
        public DbSet<ODBIORCY> ODBIORCY { get; set; }
        public DbSet<PACZKI> PACZKI { get; set; }
        public DbSet<PAŃSTWA> PAŃSTWA { get; set; }
        public DbSet<PŁATNOŚCI> PŁATNOŚCI { get; set; }
        public DbSet<POJAZDY_KURIERSKIE> POJAZDY_KURIERSKIE { get; set; }
        public DbSet<PRACOWNICY> PRACOWNICY { get; set; }
        public DbSet<PRZESYŁKI> PRZESYŁKI { get; set; }
        public DbSet<STATUS_PRZESYŁKI> STATUS_PRZESYŁKI { get; set; }
        public DbSet<TYPY_KONT> TYPY_KONT { get; set; }
        public DbSet<TYPY_LOKALIZACJI> TYPY_LOKALIZACJI { get; set; }
        public DbSet<TYPY_PACZEK> TYPY_PACZEK { get; set; }
        public DbSet<TYPY_PŁATNOŚCI> TYPY_PŁATNOŚCI { get; set; }
        public DbSet<TYPY_POJAZDÓW_KURIERSKICH> TYPY_POJAZDÓW_KURIERSKICH { get; set; }
        public DbSet<TYPY_PRACOWNIKÓW> TYPY_PRACOWNIKÓW { get; set; }
        public DbSet<TYPY_PRZESYŁEK> TYPY_PRZESYŁEK { get; set; }
        public DbSet<WOJEWÓDZTWA> WOJEWÓDZTWA { get; set; }
    
        public virtual int GENERUJ_ADRESY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GENERUJ_ADRESY");
        }
    
        public virtual int GENERUJ_KONTA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GENERUJ_KONTA");
        }
    
        public virtual int GENERUJ_KURIERZY_POJAZDY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GENERUJ_KURIERZY_POJAZDY");
        }
    
        public virtual int GENERUJ_LOKALIZACJE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GENERUJ_LOKALIZACJE");
        }
    
        public virtual int GENERUJ_NADAWCÓW()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GENERUJ_NADAWCÓW");
        }
    
        public virtual int GENERUJ_ODBIORCÓW()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GENERUJ_ODBIORCÓW");
        }
    
        public virtual int GENERUJ_PACZKI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GENERUJ_PACZKI");
        }
    
        public virtual int GENERUJ_PŁATNOŚCI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GENERUJ_PŁATNOŚCI");
        }
    
        public virtual int GENERUJ_POJAZDY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GENERUJ_POJAZDY");
        }
    
        public virtual int GENERUJ_PRACOWNIKÓW()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GENERUJ_PRACOWNIKÓW");
        }
    
        public virtual int GENERUJ_PRZESYŁKI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GENERUJ_PRZESYŁKI");
        }
    
        public virtual int GENERUJ_SZEFOWIE_PODWŁADNI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GENERUJ_SZEFOWIE_PODWŁADNI");
        }
    }
}
