//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCompanyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACZKI
    {
        public decimal ID_PACZKI { get; set; }
        public decimal ID_PRZESYŁKI { get; set; }
        public decimal ID_LOKALIZACJI { get; set; }
        public decimal TYP_PACZKI { get; set; }
        public decimal MASA_PACZKI { get; set; }
        public decimal WYMIARY_PACZKI { get; set; }
    
        public virtual LOKALIZACJE LOKALIZACJE { get; set; }
        public virtual TYPY_PACZEK TYPY_PACZEK { get; set; }
        public virtual PRZESYŁKI PRZESYŁKI { get; set; }
    }
}
