//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCompanyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAŃSTWA
    {
        public PAŃSTWA()
        {
            this.ADRESY = new HashSet<ADRESY>();
            this.WOJEWÓDZTWA = new HashSet<WOJEWÓDZTWA>();
        }
    
        public decimal ID_PAŃSTWA { get; set; }
        public string PAŃSTWO { get; set; }
    
        public virtual ICollection<ADRESY> ADRESY { get; set; }
        public virtual ICollection<WOJEWÓDZTWA> WOJEWÓDZTWA { get; set; }
    }
}
