//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCompanyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACOWNICY
    {
        public PRACOWNICY()
        {
            this.KURIERZY_POJAZDY = new HashSet<KURIERZY_POJAZDY>();
            this.PRZESYŁKI = new HashSet<PRZESYŁKI>();
            this.PRACOWNICY1 = new HashSet<PRACOWNICY>();
            this.PRACOWNICY2 = new HashSet<PRACOWNICY>();
        }
    
        public decimal ID_PRACOWNIKA { get; set; }
        public decimal TYP_PRACOWNIKA { get; set; }
        public decimal ADRES_ZAMIESZKANIA { get; set; }
        public decimal ID_LOKALIZACJI { get; set; }
        public decimal ID_KONTA { get; set; }
        public string PIERWSZE_IMIE { get; set; }
        public string DRUGIE_IMIE { get; set; }
        public string NAZWISKO { get; set; }
        public decimal WYNAGRODZENIE { get; set; }
    
        public virtual ADRESY ADRESY { get; set; }
        public virtual KONTA KONTA { get; set; }
        public virtual ICollection<KURIERZY_POJAZDY> KURIERZY_POJAZDY { get; set; }
        public virtual LOKALIZACJE LOKALIZACJE { get; set; }
        public virtual ICollection<PRZESYŁKI> PRZESYŁKI { get; set; }
        public virtual TYPY_PRACOWNIKÓW TYPY_PRACOWNIKÓW { get; set; }
        public virtual ICollection<PRACOWNICY> PRACOWNICY1 { get; set; }
        public virtual ICollection<PRACOWNICY> PRACOWNICY2 { get; set; }
    }
}
