//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCompanyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRZESYŁKI
    {
        public PRZESYŁKI()
        {
            this.PACZKI = new HashSet<PACZKI>();
        }
    
        public decimal ID_PRZESYŁKI { get; set; }
        public decimal ID_NADAWCY { get; set; }
        public decimal ID_ODBIORCY { get; set; }
        public decimal ID_KURIERA_DOSTARCZAJĄCEGO { get; set; }
        public decimal TYP_PRZESYŁKI { get; set; }
        public decimal STATUS_PRZESYŁKI { get; set; }
        public decimal ID_ADRESU_POCZĄTKOWEGO { get; set; }
        public decimal ID_ADRESU_KOŃCOWEGO { get; set; }
        public decimal ID_PŁATNOŚCI { get; set; }
        public System.DateTime DATA_NADANIA_PRZESYŁKI { get; set; }
        public System.DateTime DATA_ODEBRANIA_PRZESYŁKI { get; set; }
        public decimal KOSZT_PRZESYŁKI { get; set; }
    
        public virtual ADRESY ADRESY { get; set; }
        public virtual ADRESY ADRESY1 { get; set; }
        public virtual NADAWCY NADAWCY { get; set; }
        public virtual ODBIORCY ODBIORCY { get; set; }
        public virtual ICollection<PACZKI> PACZKI { get; set; }
        public virtual PŁATNOŚCI PŁATNOŚCI { get; set; }
        public virtual PRACOWNICY PRACOWNICY { get; set; }
        public virtual STATUS_PRZESYŁKI STATUS_PRZESYŁKI1 { get; set; }
        public virtual TYPY_PRZESYŁEK TYPY_PRZESYŁEK { get; set; }
    }
}
