//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCompanyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPY_PACZEK
    {
        public TYPY_PACZEK()
        {
            this.PACZKI = new HashSet<PACZKI>();
        }
    
        public decimal ID_TYPU { get; set; }
        public string TYP_PACZKI { get; set; }
    
        public virtual ICollection<PACZKI> PACZKI { get; set; }
    }
}
