//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCompanyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPY_PŁATNOŚCI
    {
        public TYPY_PŁATNOŚCI()
        {
            this.PŁATNOŚCI = new HashSet<PŁATNOŚCI>();
        }
    
        public decimal ID_TYPU { get; set; }
        public string TYP_PŁATNOŚCI { get; set; }
    
        public virtual ICollection<PŁATNOŚCI> PŁATNOŚCI { get; set; }
    }
}
