//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCompanyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPY_PRACOWNIKÓW
    {
        public TYPY_PRACOWNIKÓW()
        {
            this.PRACOWNICY = new HashSet<PRACOWNICY>();
        }
    
        public decimal ID_TYPU { get; set; }
        public string TYP_PRACOWNIKA { get; set; }
    
        public virtual ICollection<PRACOWNICY> PRACOWNICY { get; set; }
    }
}
