//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCompanyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPY_PRZESYŁEK
    {
        public TYPY_PRZESYŁEK()
        {
            this.PRZESYŁKI = new HashSet<PRZESYŁKI>();
        }
    
        public decimal ID_TYPU { get; set; }
        public string TYP_PRZESYŁKI { get; set; }
    
        public virtual ICollection<PRZESYŁKI> PRZESYŁKI { get; set; }
    }
}
